language: php

php:
  - 5.6

deploy:
  skip-cleanup: true
  github-token: $GITHUB_TOKEN

env:
  global:
    - CODE_COVERAGE=false
    - MAGENTO_VERSION="^1.9"

script:
    - composer require --no-update magento/core "$MAGENTO_VERSION"
    - composer install
    - php tests/unit/phpunit-5.7.9.phar -c tests/unit/phpunit.xml
