language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - CODE_COVERAGE=false

  matrix:
    - MAGENTO_VERSION=magento-mirror-1.9.3.6

script:
    - composer install
    - echo "Start the unit tests"
    - php tests/unit/phpunit-5.7.9.phar -c tests/unit/phpunit.xml